## error vs exception

# while True:
#     try:
#         x = int(input("Please enter a number: "))
#         break
#     except ValueError:
#         print("Oops!  That was no valid number.  Try again...")
        
        
# while True:
#     try:
#         x = int(input("Please enter a number: "))
#         break
#     except ZeroDivisionError:
#         print("Oops!  That was no valid number.  Try again...")